theme: jekyll-theme-tactile
title: Creative AI Enthusiasts of Knoxville - Meetup Notes
author: Tom von Clef
description: For https://www.meetup.com/creative-ai-enthusiasts-of-knoxvillle
markdown: GFM
